baseurl = "https://intel4coro.github.io/coai-vib/"
title = "CoAI-ViB"
author = "yxzhan"
canonifyurls = true
paginate = 20
theme = "aether"

[params]
  brand = "CoAI - Interactive Research Space"

[markup]
  [markup.highlight]
    style = "igor"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files